package:
  name: sample-plugin
  version: "0.1.0"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

about:
  summary: "Sample plugin"
  home: "https://github.com/aathi-star/sample-plugin"
